In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features) # calculating z = w * x + b
    out = self.sigmoid(out)

    return out


In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.3928],
        [0.3685],
        [0.3160],
        [0.3887],
        [0.3979],
        [0.4205],
        [0.4428],
        [0.3839],
        [0.3249],
        [0.3995]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[ 0.1494, -0.4252, -0.4220, -0.3840, -0.1754]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.1553], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# A bigger **NN**

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features) # calculating z = w * x + b
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out


In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.5754],
        [0.5903],
        [0.5980],
        [0.6130],
        [0.5845],
        [0.5689],
        [0.5995],
        [0.5881],
        [0.5931],
        [0.5620]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([ 0.1320, -0.0209,  0.0520], requires_grad=True)

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Using Sequential Container

In [ ]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out


In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features)

tensor([[0.5868],
        [0.5826],
        [0.5820],
        [0.5810],
        [0.5808],
        [0.5774],
        [0.5832],
        [0.5774],
        [0.5830],
        [0.5774]], grad_fn=<SigmoidBackward0>)

In [ ]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00