In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU : Tesla T4


# Creating a Tensor:

In [ ]:
#using empty
a = torch.empty(2,3)
a

tensor([[-2.4822e+19,  4.3203e-41, -2.4822e+19],
        [ 4.3203e-41,  2.7523e+23,  9.4110e+08]])

In [ ]:
#cheking type
type(a)
# type(a[0][0])

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
# assigns random values between 0 to 1
torch.rand(2,3)

tensor([[0.9341, 0.2943, 0.7103],
        [0.5901, 0.5629, 0.8818]])

In [ ]:
#use of Seed
# To retain the numbers initiated, we can not use rand fn:
torch.rand(2,3)

tensor([[0.6766, 0.5163, 0.6858],
        [0.6170, 0.9968, 0.5647]])

In [ ]:
# The values changed!

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# custom tensors
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
# Other Methonds:

# using arange:
print(torch.arange(0,10,2))

# using linspace:
print(torch.linspace(0,10,10))

# using eye(creates identity matrix of order n)
print(torch.eye(3))

# full
print(torch.full((3,5),5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(x)

tensor([[ 1.5094e-38,  0.0000e+00,  1.3807e-38],
        [ 0.0000e+00,  1.5089e-38,  0.0000e+00],
        [-4.4642e-07,  4.3202e-41, -1.2811e+19]])

In [ ]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# torch.rand_like(x) not works because x is int tensor and rand generates random float numbers b/w 0 to 1. So not correcct.
torch.rand_like(x,dtype = torch.float32)

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

DataTypes

In [ ]:
# find data type:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([[1.0,2.0,3.0]],dtype = torch.int32)

tensor([[1, 2, 3]], dtype=torch.int32)

In [ ]:
torch.tensor([[1,2,3]],dtype = torch.float64)

tensor([[1., 2., 3.]], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

# Mathematical Operations:

## 1. Scalar operations

In [ ]:
x = torch.rand(2,3)
x

tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])

In [ ]:
# addition
x + 2
# subtraction
x -2
# multiplication
x * 2
# division
x / 2
# integer division
x // 2
# mod
x % 2
# power
x ** 2

tensor([[2.7846e-01, 6.1100e-02, 6.2550e-01],
        [1.7934e-01, 2.8558e-04, 4.8794e-02]])

## 2. Element wise Operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])
tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])


In [ ]:
# addition
a + b  #
# subtraction
a - b
# multiplication
a * b
# division
a / b
# mod
a % b
# power
a ** b

tensor([[0.9697, 0.8876, 0.5613],
        [0.9406, 0.9709, 0.1818]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# absolute:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative:
torch.negative(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,4.3,8.6,5.5])

In [ ]:
#round off
torch.round(d)

tensor([2., 4., 9., 6.])

In [ ]:
# Cieling Function
torch.ceil(d)

tensor([2., 5., 9., 6.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 4., 8., 5.])

In [ ]:
# clamp
torch.clamp(d, min = 2, max = 5)

tensor([2.0000, 4.3000, 5.0000, 5.0000])

## 3. Reduction Operations

In [ ]:
e = torch.randint(size = (2,3),dtype = torch.float32, low = 0,high = 10)
e

tensor([[5., 5., 0.],
        [4., 3., 8.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e,dim=0)
# sum along rows
torch.sum(e,dim=1)

tensor([22, 10])

In [ ]:
# mean
torch.mean(e)
# mean about col
torch.mean(e,dim=0)
# mean about row
torch.mean(e,dim = 1)

tensor([3.3333, 5.0000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.6394)

In [ ]:
# variance
torch.var(e)

tensor(6.9667)

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# arg min
torch.argmin(e)

tensor(2)

## 4. Matrix Operations

In [ ]:
f = torch.randint(size = (2,3),low = 0,high = 10)
g = torch.randint(size = (3,2),low = 3, high= 14)

print(f)
print(g)

tensor([[8, 3, 3],
        [5, 0, 6]])
tensor([[7, 9],
        [7, 4],
        [5, 6]])


In [ ]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[ 92, 102],
        [ 65,  81]])

In [ ]:
# Dot Product (defined for matrices of equal dimension only.)
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[8, 5],
        [3, 0],
        [3, 6]])

In [ ]:
# Determinant
y = torch.ones((3,3))
y

torch.det(y)

tensor(0.)

In [ ]:
# inverse
torch.inverse(y) # works fine

_LinAlgError: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

## 5. Comparison Operators